name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main]

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      migration-needed: ${{ steps.changes.outputs.migrations }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for migration changes
        id: changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -E '^supabase/migrations/.*\.sql$'; then
            echo "migrations=true" >> $GITHUB_OUTPUT
            echo "Migration files changed, migration needed"
          else
            echo "migrations=false" >> $GITHUB_OUTPUT
            echo "No migration files changed, skipping migration"
          fi

  migrate-database:
    runs-on: ubuntu-latest
    needs: [check-migrations]
    if: ${{ needs.check-migrations.outputs.migration-needed == 'true' }}
    outputs:
      migration-success: ${{ steps.migrate.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run database migration
        id: migrate
        run: npm run migrate
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

      - name: Notify migration completion
        if: success()
        run: echo "Database migration completed successfully"

  deploy-production:
    runs-on: ubuntu-latest
    needs: [check-migrations, migrate-database]
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    if: ${{ always() && (needs.check-migrations.outputs.migration-needed == 'false' || needs.migrate-database.outputs.migration-success == 'success') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install dependencies
        run: npm ci

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deployment notification
        if: success()
        run: echo "🚀 Production deployment completed successfully!"

      - name: Rollback notification
        if: failure()
        run: |
          echo "❌ Deployment failed! Manual intervention required."
          echo "Database migration was successful but deployment failed."
